/*FerreiraDaCosta_Palomeque*/

1)SELECT * FROM LUCHADOR; 
2)SELECT NOMBRE FROM LUCHADOR; 
3)SELECT NOMBRE, P1+P2+P3+P4+P5 AS PUNTAJE FROM LUCHADOR; 
4)SELECT NOMBRE, P1+P2+P3+P4+P5 AS PUNTAJE FROM LUCHADOR WHERE CATEGORIA=2 OR CATEGORIA=3; 
5)a)SELECT AVG(PESO) AS PESO_PROMEDIO FROM LUCHADOR; 
5)b)SELECT SUM(PESO) / COUNT(PESO) AS PESO_PROMEDIO FROM LUCHADOR; 
6)SELECT AVG(ALTURA) AS ALTURA_PROM, AVG(EDAD) AS EDAD_PROM FROM LUCHADOR; 
7)SELECT NOMBRE, PESO / (ALTURA * ALTURA) AS MASA_CORPORAL FROM LUCHADOR; 
8)a)SELECT AVG(PESO) AS PESO_PROM, AVG(ALTURA) AS ALTURA_PROM FROM LUCHADOR WHERE SEXO= 'M'; 
8)b)SELECT AVG(PESO) AS PESO_PROM, AVG(ALTURA) AS ALTURA_PROM FROM LUCHADOR WHERE SEXO= 'F'; 
 
