/*NICOLAS MANOGRASSO, LAUTARO D'ERCOLE */
/*1-*/	SELECT * FROM JUGADORES 
/*2-*/	SELECT NOMBRE FROM  JUGADORES
/*3-*/	SELECT NOMBRE, P1+P2+P3+P4+P5 AS P_TOTAL FROM LUCHADORES
/*4-*/	SELECT NOMBRE,CATEGORIA P1+P2+P3+P4+P5 AS P_TOTAL FROM LUCHADORES WHERE CATEGORIA = 2 OR 3 
/*5-*/	SELECT AVG(PESO ) AS PROMEDIO_PESO  FROM JUGADORES
/*B- */	SELECT SUM(PESO)/COUNT(PESO) AS PESO_PROM FROM JUGADORES 
/*6-*/	SELECT SUM(ALTURA)/COUNT(ALTURA) AS ALT_PROMEDIO
	SELECT SUM(EDAD)/COUNT(EDAD) AS EDAD_PROM FROM JUGADORES
/*7-*/	SELECT NOMBRE, PESO/(ALTURA*ALTURA) AS P_CORPORAL FROM JUGADORES
/*8-*/	SELECT AVG(PESO) AS PROM_PESO AVG(ALTURA) AS PROM_ALT FROM JUGADORES WHERE SEXO = 'M' 
	SELECT AVG(PESO) AS PROM_PESO AVG(ALTURA) AS PROM_ALT FROM JUGADORES WHERE SEXO = 'F'


