--Cristian Gnecco, Diego Azpeitia //Heladeria Los amores
CREATE TABLE FACTURA (
       PRIMARY KEY (ID_FACTURA) INTEGER,
       FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
       TIPO varchar(4),
       FECHA varchar(255)
       );

CREATE TABLE PEDIDO(
       PRIMARY KEY (ID_PEDIDO) INTEGER,
       FECHA varchar(255),
       FOREIGN KEY (ID_HELADERIA) REFERENCES HELADERIA(ID)
);

CREATE TABLE PEDIDO_SABORES(
       PRIMARY KEY (ID_SABOR) INTEGER,
       PRIMARY KEY (ID_PRECIO) INTEGER,
       PRIMARY KEY (ID_PEDIDO) INTEGER,
       FOREIGN KEY (ID_SABOR) REFERENCES SABOR_PRECIO(ID_SABOR),
       FOREIGN KEY (ID_PRECIO) REFERENCES SABOR_PRECIO(ID_PRECIO),
       FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) 
       );
CREATE TABLE SABOR_LOTE(
       PRIMARY KEY (ID_SABOR) INTEGER,
       PRIMARY KEY (ID_LOTE) INTEGER,
        FOREIGN KEY (ID_SABOR) INTEGER REFERENCES SABORES(ID_SABOR),
        FOREIGN KEY (ID_LOTE) INTEGER REFERENCES LOTE(ID_LOTE),
       CANT INTEGER
       );
CREATE TABLE PRECIO(
       PRIMARY KEY (ID_PRECIO) INTEGER,
       PRECIO INTEGER,
       FECHA varchar(15)
       );
CREATE TABLE SABOR_PRECIO(
       PRIMARY KEY (ID_SABOR) INTEGER,
       PRIMARY KEY (ID_PRECIO) INTEGER,
       FOREIGN KEY (ID_SABOR) INTEGER REFERENCES PEDIDO_SABORES(ID_SABOR),
       FOREIGN KEY (ID_PRECIO) INTEGER REFERENCES PRECIO(ID_PRECIO) 
       );

CREATE TABLE HELADERIA(
       PRIMARY KEY (ID) INTEGER ,
       NOMBRE varchar(255),
       CUIT INTEGER,
       DOMICILIO varchar(255)
       );

CREATE TABLE LOTE(
       PRIMARY KEY (ID_LOTE) INTEGER,
       FECHA varchar(255)
       );

CREATE TABLE SABORES(
       PRIMARY KEY (D_SABOR) INTEGER,
       NOMBRE varchar(255)
       );

CREATE TABLE MATERIA_PRIMA(
       PRIMARY KEY (ID_INGREDIENTE) INTEGER,
       FOREIGN KEY (ID_INGREDIENTE) INTEGER REFERENCES INGREDIENTES(ID),
       CANT_INGREDIENTE INTEGER,
       FECHA varchar(255)
       );      

CREATE TABLE INGREDIENTES(
       PRIMARY KEY (ID) INTEGER,
       NOMBRE varchar(255)
       );

CREATE TABLE INGREDIENTES_SABOR(
       PRIMARY KEY (ID_SABOR) INTEGER,
       PRIMARY KEY (ID_INGREDIENTE) INTEGER,
       FOREIGN KEY (ID_SABOR) REFERENCES SABORES(ID_SABOR),
       FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID_INGREDIENTE),
       CANT INTEGER
       );       
